### ISSUE TITLE
Move stations UUID map to separate data file

### ISSUE THREAD

**Issue by hrbonz** [gams/openkongqi#2]
Move the UUID map to either:

* database structure: will need database + data dump for initial import
* flat file: one folder with all files ('cc-state-city.json' or 'cc-city.json') or use nested folders ('cc/state/city.json', 'cc/city.json')

**Comment by eddowh** [comment]
I was wondering about CSVs... but that would fall closer to the database structure format, so I'm not exactly sure what other formats are available. I've heard of XML but never really learned about it (from what I know it's structured with tags like html?)

**Comment by eddowh** [comment]
Another *questionable* alternative would be to store the data as YAML as opposed to JSON.

Some other YAML-like options mentioned in this [Hacker News thread](https://news.ycombinator.com/item?id=9332202):
- [TOML](https://github.com/toml-lang/toml)
- [Hjson](http://hjson.org/)

**Comment by hrbonz** [comment]
CSV is not easy to read and easy to break, I prefer the verbosity of json.
XML is also verbose but too much for my taste, you often end up writing as
much data description as data itself.
I don't like yaml so much because I find it not so intuitive but that's
more a personal opinion.

Stefan, from my mobile
-- 
Stefan Berder (白峰)
CEO
(+86) 186 2177 6391
Our measure of quality

**Comment by eddowh** [comment]
By the way, from the looks of it, right now we are just considering the representations of data format for the stations. But as time passes and our nested data grows bigger, will we have to use **gzipped JSON** to deal with the size?

**Comment by hrbonz** [comment]
Let's stick to JSON for now, you think too much in terms of data interchange when it's really simply a data dump in that case.
Gzipped JSON will not bring anything to this problem, the space gain on disk will probably not be significant and I would have to use my precious CPU cycles to decompress it when starting openkongqi.

**Comment by eddowh** [comment]
I think this can be closed now.

**Comment by hrbonz** [comment]
Closed by 99a4a1c02c765f2e380d5250013659ea2c1333c3
