### ISSUE TITLE
Why use `bs4` (BeautifulSoup) over `lxml`?

### ISSUE THREAD

**Issue by eddowh** [gams/openkongqi#32]
When I was watching tutorials on Python web scraping to get myself acquainted, I started out with `bs4` (BeautifulSoup). But as I tried using it for demos and whatnot I realize that `bs4`'s parsing speeds can be widely inconsistent - I encountered this problem when i was scraping for the user agent strings and I was confused as to why the deviation of the speeds were high.

On the other hand, I discovered another widely well-known HTML/XML parsing library called `lxml`, which is implemented in C, Python, & Cython. All of the testimonials out there support the fact that `lxml` is faster and more efficient and whatnot.

Now I know that right now the data we're fetching and extracting are such small chunks that the results are not noticeable. I was just wondering at what point does a project consider favoring `lxml` over `bs4`? What is the threshold of the web data size to which developers should choose `lxml`?

**Comment by hrbonz** [comment]
You can use `lxml` as a parser (see http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser), I usually use `html5lib` for flexibility with broken HTML.
