### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by hrbonz** [gams/openkongqi#6]
The repository migration broke travis, fix it!

**Comment by eddowh** [comment]
http://stackoverflow.com/questions/13886218/remove-travis-ci-old-builds

**Comment by eddowh** [comment]
Hey look! Why is there an [`openkongqi-clean`](https://travis-ci.org/gams/openkongqi-clean) repository that is just building all the time?

**Comment by hrbonz** [comment]
You'll have to show me, I don't see this.

**Comment by eddowh** [comment]
Can you go to https://travis-ci.org/profile/gams and flip the switch on for `openkongqi`? It requires admin rights and I don't think I have them.

**Comment by eddowh** [comment]
Classic IT solution of "have you tried turning it on and off again?". Closing this.
