### ISSUE TITLE
Remove wildcard "*" when building UUID

### ISSUE THREAD

**Issue by libokj** [gams/openkongqi#72]
![image](https://user-images.githubusercontent.com/66983285/103346834-36ebad00-4ad0-11eb-98e0-ad653938a047.png)

Replace wildcard with the respective region name when building the UUID (e.g. `okq:cnemc:cn:cnemc:*:1524a:latest` should be `okq:cnemc:cn:cnemc:hunan:zhuzhou:1524a:latest`).

Potentially relevant code:
https://github.com/gams/openkongqi/blob/c7d94c2f14e85f0a64f3796a08ea3023b0f8681f/openkongqi/utils.py#L29

**Comment by hrbonz** [comment]
I think the best way to solve the current problem is to inject the bits covered by the wildcard as a prefix to the station UUID.

In the test example with `us:*`, the keys in `openkongqi.stations._STATIONS_MAP` are `us:ca` and `us:oh`.

### TODO

* Drop the wildcard suffix when building a uuid in `openkongqi.utils.get_uuid(*args)`:
```py
SEP.join([frag.replace(SEP + WILDCARD, "") for frag in args])
```
* Create a `openkongqi.stations._inject_uuid_prefix(prefix, map)` that takes a station map, creates a copy of all items where it injects the prefix at the start of the uuid and return that new map.
*  Use the prefix injection function in `openkongqi.stations.get_station_map(uuid)` to inject the remaining of `k` when removing the wildcarded protion of the uuid.
